insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('1111','Virat');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('2222','Ronaldo');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('3333','Sachin');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('4444','Bumhra');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('5555','Ashwin');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('6666','Virat');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('7777','Kartik');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('8888','Kishan');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('9999','Vijay');
insert into Customer(CUSTOMER_ID,CUSTOMER_NAME) values ('1000','Messy');
commit;